services:

  postgres:
    image: 'postgres:latest'
    container_name: fileUploader-db
    environment:
      - POSTGRES_DB=fileUploader
      - POSTGRES_PASSWORD=Youcode@2023
      - POSTGRES_USER=postgres
      - PGDATA=/data/postgres
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - fileUploader

  redis:
    image: 'redis:latest'
    container_name: fileUploader-redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - fileUploader

  app:
    container_name: fileUploader-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8082"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - fileUploader

networks:
  fileUploader:
    attachable: true
    name: fileUploader
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:0DB9::/112


volumes:
  postgres-db:
    driver: local